name = "healthwatchifier"
main = "src/index.js"
compatibility_date = "2025-07-04"
compatibility_flags = ["nodejs_compat"]

routes = [
  "strikethroughediting.ca/*",
  "www.strikethroughediting.ca/*"
]

[observability]
enabled = true

[[kv_namespaces]]
binding = "LINKEDIN_FEED"
id = "5bc12df991a346f1bdfac19f7f8e2eaf"
preview_id = "5bc12df991a346f1bdfac19f7f8e2eaf"